### ISSUE TITLE
multiple return status codes

### ISSUE THREAD

**Issue by dyens** [jmcarp/flask-apispec#109]
I have a auth function. If  input params (login, pass) is valid i return token and 200 status code. Otherwise, i want return something like None or '' and staus code=401.
This code raise exception when  {some_condition} is True:

```
    @marshal_with(None,
                  description='Wrong user or password',
                  code=401
    )
    @marshal_with(TokenSchema,
                  description='Token auth',
                  code=200
    )
    def post(self, **kwargs):
         if some_condition:
            return None, 401
         else:
            return Token(), 200
             
```

File "/home/user/.local/share/virtualenvs/venv/lib/python3.6/site-packages/flask_apispec/wrapper.py", line 58, in marshal_result
    dumped = schema.dump(unpacked[0])
AttributeError: 'dict' object has no attribute 'dump'

How can i describe multiple status code returns?

**Comment by dyens** [comment]
I found this solution:

class NoneSchema(ma.Schema):
    pass

    @marshal_with(NoneSchema,
                  description='Wrong user or password',
                  code=401
    )
    @marshal_with(TokenSchema,
                  description='Token auth',
                  code=200
    )
    def post(self, **kwargs):
         if some_condition:
            return None, 401
         else:
            return Token(), 200

**Comment by anandtripathi5** [comment]
You can also use the @doc statement for it, as doc is directly providing its argument to swagger docs
`
@doc(description="test description", tags=['test tag'], responses={
"401": {
            "description": "Wrong user or password",
            "schema": {
              "properties": {}
            }
        }
})
`
