### ISSUE TITLE
Cannot import swagger from apispec v0.39

### ISSUE THREAD

**Issue by l9c** [jmcarp/flask-apispec#110]
Swagger has been changed to OpenAPI https://github.com/marshmallow-code/apispec/commit/d0ad59e2d9a9c91c9cea28b3b7718420b1b1111d

**Comment by lbeaufort** [comment]
Hi there! It looks like [this commit](https://github.com/jmcarp/flask-apispec/commit/435cc031b1fac01c7a7c8da038d8b82e446676ba#diff-9db0759383c9c97813a6558091c47452) and version 0.7.0 addresses this issue.
