### ISSUE TITLE
Swagger auto generate the OPTIONS method 

### ISSUE THREAD

**Issue by ruathudo** [jmcarp/flask-apispec#111]
Is it normal or an issue when swagger auto creating OPTIONS method when using with others methods (GET, POST...)?
How to ignore the options method? Thanks

![image](https://user-images.githubusercontent.com/3640787/42936695-74c3fda4-8b55-11e8-9d10-09b85b6c7212.png)

**Comment by blagasz** [comment]
It is actually a Flask feature described here: http://flask.pocoo.org/docs/1.0/api/#view-function-options

**Comment by blagasz** [comment]
Sorry I've seen your quickfix just now...

**Comment by ruathudo** [comment]
I created a pull request for this here. If someone can merge it.
https://github.com/jmcarp/flask-apispec/pull/112

**Comment by janhui** [comment]
I also would like this feature where I can stop showing the options endpoint if I don't want to. There are 2 pull request open to deal with this issue, it would be good to get a pointer on which direction we want to go with and get the pr merged into master. @jmcarp @sloria

**Comment by guidiego** [comment]
You could make a workaround using FlaskApiSpec instance :) On my application, I allocate the instance inside `app.__docs__`

```python
for key, value in app.__docs__.spec._paths.items():
        app.__docs__.spec._paths[key] = {
            inner_key: inner_value
            for inner_key, inner_value in value.items()
            if inner_key != 'options'
        }
```

This should remove all options from ur API without killing the CORS functionallity of your app :)
