### ISSUE TITLE
Nested recursive object

### ISSUE THREAD

**Issue by enjoy2000** [jmcarp/flask-apispec#117]
I got this error when trying to do nested recursive for an object:

```
builtins.RecursionError
RecursionError: maximum recursion depth exceeded
```

I did try to check `marshmallow` and `apispec` libs, they both support it tho. Not sure why I cannot use here.

I'm using `flask-apispec==0.7.0`

**Comment by henryfjordan** [comment]
it's not that you cannot recurse, it's that your Python process literally runs out memory in the call stack and throws an error because you recurse infinitely.

Make sure that whatever you are recursing through has some end/base case.
