### ISSUE TITLE
Validation of minimum/maximum of field.Int

### ISSUE THREAD

**Issue by YnkDK** [jmcarp/flask-apispec#136]
If I have the following schema:
````python
class MySchema(Schema):
    port = fields.Int(minimum=0, maximum=65535)
````
and I use it in the decorator `use_kwargs(MySchema)` the limits are shown perfectly in the swagger documentation, but if I request my request looks like `{"port": 15610165}` it just passes though to my POST method in my resource. 

This indicates that the method ignores the limits when parsing the input, but the swagger documentation respects the limits.

**Comment by decaz** [comment]
```python
from marshmallow.validate import Range

class MySchema(Schema):
    port = fields.Int(validate=Range(0, 65535))
```

**Comment by sloria** [comment]
@decaz is correct; you need to use th me validator. Setting minimum and maximum on the field has no effect other than adding to the field’s metadata.
