### ISSUE TITLE
Documenting individual fields

### ISSUE THREAD

**Issue by IamJeffG** [jmcarp/flask-apispec#157]
I am migrating an old web service away from Flask-RESTPlus, to `flask-apispec`.  A feature in RESTPlus allowed documenting each individual field in a schema with an optional `description=` string:  https://flask-restplus.readthedocs.io/en/stable/swagger.html#documenting-the-fields

We use this all the time, since the consumers of this Flask API are totally different teams with very little background knowledge about what it is they're getting back.  It's a very useful communication tool.

Is there any support (hacky or elegant) for something similar with marshmallow and/or apispec?

**Comment by sloria** [comment]
apispec respects the `description` kwarg passed to fields, so it _should_ work with flask-apispec: https://apispec.readthedocs.io/en/stable/api_ext.html#module-apispec.ext.marshmallow

**Comment by IamJeffG** [comment]
Easy!  It works, sorry I missed that before opening the ticket.
