### ISSUE TITLE
Upgrade from 0.4.2 version

### ISSUE THREAD

**Issue by polozhevets** [jmcarp/flask-apispec#180]
https://github.com/jmcarp/flask-apispec/blob/55255f5c30cacb7dd14668ed5e01cb9e03280419/flask_apispec/wrapper.py#L46

>   File "/usr/local/lib/python3.6/site-packages/flask_apispec/wrapper.py", line 46, in call_view
    parsed = parser.parse(schema, locations=option['kwargs']['locations'])
TypeError: parse() got an unexpected keyword argument 'locations

Just updated to the latest version and got this error 😳

**Comment by sloria** [comment]
What version of webargs do you have installed? flask-apispec is not yet compatible with webargs 6, which is why it is currently pinned to `webargs<6.0`.

**Comment by polozhevets** [comment]
Yeah, I have 6.0.0. Which version is recommended?

**Comment by sloria** [comment]
5.5.3 is the latest version before 6.0.0

**Comment by polozhevets** [comment]
Thanks!
