### ISSUE TITLE
The use_kwargs and marshal_with decorators skip response headers

### ISSUE THREAD

**Issue by ketgo** [jmcarp/flask-apispec#183]
When using the `use_kwargs` and `marsha_with` decorators, any custom headers returned by a view function gets skiped in response. An example code:
```python
from flask import Flask
from flask.views import MethodView
from flask_apispec import marshal_with
from marshmallow import Schema, fields

app = Flask(__name__)

class TestSchema(Schema):
    name = fields.String()

class TestResource(MethodView):

    @marshal_with(TestSchema)
    def get(self):
        return {"name": "github"}, 200, {"Etag": "12345"}

app.add_url_rule('/test', view_func=TestResource.as_view('test'))

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

Here the `Etag` response header is not sent by the server when a `GET` request is sent to the `/test` path even though it's being returned in the view function. If the `marshal_with` decorator is removed no issue is observed. Similar is the case for also the `use_kwargs` decorator.

**Comment by c-kruse** [comment]
I think this is a duplicate of this issue. https://github.com/jmcarp/flask-apispec/issues/181

**Comment by ketgo** [comment]
Thanks, it is duplicate.
