### ISSUE TITLE
README.rst is outdated

### ISSUE THREAD

**Issue by henadzit** [jmcarp/flask-apispec#19]
The constructor interface of FlaskApiSpec was changed in https://github.com/jmcarp/flask-apispec/commit/581d07501aacdcd4462f4f187489604e99793ffa but README still has the previous format.

**Comment by rth** [comment]
@henadzit a PR to fix this inconsistency would be welcome.

**Comment by ffleandro** [comment]
Also, manual installation needs a `invoke install` before `python setup.py install`.

**Comment by sloria** [comment]
Thanks @mikeabrahamsen for the PR and thanks @ffleandro for pointing out the missing installation docs. They have been updated.
