### ISSUE TITLE
How to surface underlying marshmallow error in 422 API response

### ISSUE THREAD

**Issue by opyate** [jmcarp/flask-apispec#190]
Hi, at the moment my API just responds with

> {UnprocessableEntity}422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.

How can I get the underlying marshmallow error surfaced? It will give consumers a clearer idea of what went wrong.

**Comment by zartstrom** [comment]
Hi @opyate, I have the same question. Did you figure it out?!

**Comment by opyate** [comment]
I had `FLASK_DEBUG` set, so were seeing the HTML/stacktrace error, not the Marshmallow JSON error. Rookie! :)
