### ISSUE TITLE
apispec 4.0.0

### ISSUE THREAD

**Issue by mdantonio** [jmcarp/flask-apispec#202]
apispec just released a new version containing breaking changes

and it is installed due to setup requirements:

```
REQUIRES = [
    [...]
    'apispec>=1.0.0',
]
```

Error:

```
/usr/local/lib/python3.8/dist-packages/flask_apispec/apidoc.py:92: in get_parameters
    converter = openapi.fields2parameters
E   AttributeError: 'OpenAPIConverter' object has no attribute 'fields2parameters'
```

This is from the changelog of apispec:

> Refactoring:
> 
> OpenAPIConverter.field2parameters and OpenAPIConverter.property2parameter are removed.
> OpenAPIConverter.field2parameter becomes private. (:pr:`581`)

As a temporary fix (while working to support apispec 4.x) a 

```
REQUIRES = [
    [...]
    'apispec>=1.0.0,<4',
]
```

would be helpful

**Comment by subhamagr** [comment]
Are there any patch release for the issue?

**Comment by catalanojuan** [comment]
hey there, I just opened https://github.com/jmcarp/flask-apispec/pull/204 that solves this issue

**Comment by kam193** [comment]
I introduced PR #206 with try to compatibility for apispec >= 4. This is backwards-incompatible change since apispec 4 has no backward compatibility - so I think the release with apispec pined to <4 should be released anyway.

cc: @sloria
