### ISSUE TITLE
Add init_app() method to FlaskApiSpec

### ISSUE THREAD

**Issue by lafrech** [jmcarp/flask-apispec#21]
I'm experiencing with flask-apispec on an application using blueprints, getting inspiration from @frol's comprehensive example (https://github.com/jmcarp/flask-apispec/issues/17).

I'm using an [application factory](http://flask.pocoo.org/docs/0.10/patterns/appfactories/) so I modified FlaskApiSpec to add an `init_app` method.

The `__init__.py` file of the application reads:

``` python
db = MongoEngine()
docs = FlaskApiSpec()

def create_app(flask_config='development', **kwargs):

    app = Flask(__name__, **kwargs)

    config_name = os.getenv('FLASK_CONFIG', flask_config)
    app.config.from_object(CONFIGS[config_name])

    db.init_app(app)
    docs.init_app(app)

    from . import modules
    modules.init_app(app)

    return app

```

[Here](https://github.com/Nobatek/flask-apispec/commit/6890d382ea9485fcf5538da5e17d9a49589f88d9)'s the patch.

Does this make sense? Any advice, anyone?

The `init_app` pattern seems quite widespread. I'd happily send a PR, but the change most certainly needs polishing before reaching integration quality.

**Comment by frol** [comment]
@lafrech This makes sense! I'm happy that my example inspired you to make this project better!

**Comment by sloria** [comment]
Done in https://github.com/jmcarp/flask-apispec/pull/31
