### ISSUE TITLE
Securing Swagger UI Pages

### ISSUE THREAD

**Issue by antrogers** [jmcarp/flask-apispec#212]
Hi, is there any documentation on how to secure your swagger-json and swagger-ui pages? I have tried adding a basic @app.before_request function that checks if 'swagger' or 'swagger-ui' is in the url and if that passes then checks to see if a password query parameter matches the one I have set, but then I run into "Unable to render this definition The provided definition does not specify a valid version field. Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0)." If you could send me in the right direction on this I would be grateful. Thanks for all the code :)

```
@app.before_request 
def before_request_func():
    if re.search('swagger-ui', request.url) is not None or re.search('swagger', request.url) is not None:
        pw = request.args.get('pw')
        if pw != "blahblah/":
            return jsonify("Not authorised to view page.")
```

**Comment by romanhirsh-guardicore** [comment]
@antrogers I ended up disabling the default endpoints 

`app.config.update({
    'APISPEC_SPEC': api_spec,
    'APISPEC_SWAGGER_URL': '',  # URI to access API Doc JSON
    'APISPEC_SWAGGER_UI_URL': ''  # URI to access UI of API Doc
})`

And created my own resource which requires token authentication
`
class SwaggerResource(Resource):
    def get(self):
        return self.response

    @classmethod
    def set_response(cls, response):
        cls.response = response
        return cls
`
And set response to FlaskApiSpec.spec.to_dict()


`
docs = FlaskApiSpec(api.app)

api.add_resource(SwaggerResource.set_response(docs.spec.to_dict()), 'swagger-json', methods=['GET'])`

**Comment by antrogers** [comment]
@romanhirsh-guardicore Thank you! That’s neat. Will implement same
