### ISSUE TITLE
MethodViewType removed in Flask 2.2

### ISSUE THREAD

**Issue by woutdenolf** [jmcarp/flask-apispec#237]
See: https://github.com/pallets/flask/commit/45174bf9a1e96e51ce589c7aa2c151249d1fdf11

In `Flask < 2.2`
```
class MethodView(View, metaclass=MethodViewType):
```
In `Flask >= 2.2`
```
class MethodView(View):
    def __init_subclass__(cls, **kwargs: t.Any) -> None:
```

**Comment by MarkShawn2020** [comment]
> See: [pallets/flask@45174bf](https://github.com/pallets/flask/commit/45174bf9a1e96e51ce589c7aa2c151249d1fdf11)
> 
> In `Flask < 2.2`
> 
> ```
> class MethodView(View, metaclass=MethodViewType):
> ```
> 
> In `Flask >= 2.2`
> 
> ```
> class MethodView(View):
>     def __init_subclass__(cls, **kwargs: t.Any) -> None:
> ```

Thanks, you do save me a lot of time!

**Comment by ischaojie** [comment]
Same issue as.

**Comment by derlikh-smart** [comment]
related to https://github.com/pallets/flask/pull/4624
