### ISSUE TITLE
Maintenance of flask-apispec

### ISSUE THREAD

**Issue by rth** [jmcarp/flask-apispec#26]
Flask-apispec looks like a great project with a functionality that's definitely needed for flask based apps. I'm considering using it for one of my projects, however I'm slightly worried by the current state of development and the future of this project:  the last few issues were not answered, PRs not merged (issue #20) and last commit dates back to Dec 2015. 

@jmcarp I understand that you are now busy with other projects which is perfectly understandable. 
Lately there was some work on flask-apispec done by @msscully, @lafrech, @incognick, @tejovanthn, @ciaran-stackworx and @houjunchen in their respective forks. Maybe somebody would have the time (and the inclination) to occasionally maintain this package (and merge PRs) if either they got write access to this repo, or alternatively if the development moved to one of the forks? Thanks.

**Comment by sloria** [comment]
I am a collaborator on this project. This project will still be maintained, though it is a bit slower at the moment. @jmcarp has moved off the work project for which this package was built, and I am not currently using this at my day job.

I'll try to give more attention to this project and review/merge PRs when I can. Any help reviewing PRs would be greatly appreciated.

**Comment by rth** [comment]
That is great, thank you for your response, @sloria ! I will try to help a bit with reviewing PR's.

**Comment by sloria** [comment]
Thanks for your help!
