### ISSUE TITLE
Blank page http://localhost:5000/swagger-ui/

### ISSUE THREAD

**Issue by FrancescElies** [jmcarp/flask-apispec#28]
Hi,

if I try the example `$ python examples/petstore.py` and I visit `http://localhost:5000/swagger` I get the swagger definition spec, but if I visit `http://localhost:5000/swagger-ui/` I get a blank page, is this right? What should I be able to see there?

Thanks in advance for any help

**Comment by elatomo** [comment]
Hi @FrancescElies, if you are running `examples/petstore.py` from a cloned copy of this repository, you'll have to fetch the _swagger-ui_ dependencies: `invoke install`.

**Comment by FrancescElies** [comment]
lovely, thanks!
That solved the issue, closing

**Comment by ffleandro** [comment]
If I'm using `flask-apispec` installed via pip, what is the procedure for providing `swagger-ui`?
Do I have to clone the `swagger-ui` repository manually and copy the files? Copy to where?
Am I missing something or should this be better documented?

**Comment by FrancescElies** [comment]
Does this help? https://github.com/jmcarp/flask-apispec/blob/3ab1e816e3c54c8361de1df7a7a9450ce5b0c523/docs/install.rst
```
$ pip install invoke
$ invoke install
$ python setup.py install
```

**Comment by ffleandro** [comment]
That would imply I downloaded the flask-apispec repository.

What about when installed via pip?

Em 07/06/2017 05:12, "Francesc Elies" <notifications@github.com> escreveu:

**Comment by FrancescElies** [comment]
You are right, in that case not sure. Maybe the maintainers know what to do in that case
