### ISSUE TITLE
AssertionError: Schemas with many=True are only supported for 'json' location

### ISSUE THREAD

**Issue by luisincrespo** [jmcarp/flask-apispec#34]
Hi, I'm getting the following error:

```
AssertionError: Schemas with many=True are only supported for 'json' location
```

When trying to do this:

```python
@use_kwargs(MySchema(many=True, only=('attr1', 'attr2'), partial=True))
def post(self, **kwargs):
```

It still complains if I do this (specify locations):

```python
@use_kwargs(MySchema(many=True, only=('attr1', 'attr2'), partial=True), locations=['json'])
def post(self, **kwargs):
```

Are there any known issues around this? Thanks!

**Comment by rth** [comment]
@luisincrespo How about,
```py
@use_kwargs(MySchema(many=True, only=('attr1', 'attr2'), partial=True), locations=['body'])
[..]
```
does that work? 

The exception is raised in [`fields2parameters`](https://github.com/marshmallow-code/apispec/blob/02b08b9b1fe96b47e4e11447240f0b1aad89b87b/apispec/ext/marshmallow/swagger.py#L337) inside apispec, and the `default_in` parameter is assigned [here](https://github.com/jmcarp/flask-apispec/blob/2f8429ca8e4fa4dd9c0dee12a721f2abd36a9778/flask_apispec/apidoc.py#L67) inside flask-apispec. Though `default_in="body"` appears to be the default, as far as I could tell. 

I though that `@use_kwargs` would parse the body (not the URL encoded parameters) by default for a POST request?

**Comment by luisincrespo** [comment]
@rth thanks for answering. If I change `locations=['json']` to `locations=['body']`, I still get an error, now coming from `webargs`:

```
assert 'json' in locations, "schema.many=True is only supported for JSON location"
```

`@use_kwargs` works as expected for POST requests without `many=True`

**Comment by luisincrespo** [comment]
A possible solution would to change [this](https://github.com/jmcarp/flask-apispec/blob/2f8429ca8e4fa4dd9c0dee12a721f2abd36a9778/flask_apispec/apidoc.py#L67) so it sets `default_in="body"` when `locations[0]` is `json`.

**Comment by luisincrespo** [comment]
I opened a PR, not sure if it's something you'd be interested in @jmcarp

**Comment by rth** [comment]
Here is an example that reproduces this issue,
```py
from flask import Flask
from webargs import fields
from flask import request
from marshmallow import Schema
from flask_apispec import use_kwargs
from webargs.flaskparser import use_args
import json

app = Flask(__name__)

class MySchema(Schema):
    a = fields.Int()

@app.route('/', methods=['POST'])
@use_kwargs(MySchema(strict=True, many=True))
def index(**args):
    print('URL', request.full_path)
    print('Headers', request.headers)
    print('Data', request.data)
    print('Parsed args:', args)
    return ''

if __name__ == '__main__':
    app.config['TESTING'] = True
    test_app = app.test_client()
    test_app.post(data=json.dumps([{"a": 2}, {"a": 3}]),
                  content_type='application/json')
```

I don't think that specifying location is a solution: for other schemes the location is determined correctly even when it's not explicitly specified.

I might be wrong, but it feels like apispec does not support such schemes because they might not be compatible with OpenAPI specs? For instance replacing, 
```py
@use_kwargs(MySchema(strict=True, many=True))
```
in the above example with
```py
@use_kwargs({'data': fields.Nested(MySchema(strict=True, many=True))})
```
works fine (without specifying the location)..
