### ISSUE TITLE
New TAG with latest changes

### ISSUE THREAD

**Issue by ffleandro** [jmcarp/flask-apispec#39]
Can you please release a new version, since a few things have happened since `1.3.2`, for instance, the `init_app` instantiation method.

**Comment by rth** [comment]
That would be a really good idea. The last one `1.3.2` was uploaded to PyPi on 2015-12-07 ...

**Comment by sloria** [comment]
I don't have access to the PyPI repository. @jmcarp Could you please give me access or cut the release yourself?

**Comment by sloria** [comment]
@rth I would prefer to have tags correspond to PyPI releases. For the time being, I recommend pinning to a git commit.

**Comment by sloria** [comment]
@jmcarp has given me PyPI access. 0.4.0 is released!
