### ISSUE TITLE
can you include example usage with flask-restful and flask-classful

### ISSUE THREAD

**Issue by AlJohri** [jmcarp/flask-apispec#54]
- https://github.com/teracyhq/flask-classful
- https://flask-restful.readthedocs.io/en/0.3.5/

I'm having a bit of trouble understanding how to use this outside of `MethodResource`

**Comment by AlJohri** [comment]
Here's an example attempt at using flask-classful: https://github.com/AlJohri/nonworking-flask-apispec-example/blob/master/app.py

These are the instructions to run it:

```
export DATABASE_URL=postgresql://localhost/test_app FLASK_APP=app.py
createdb test_app
flask db init
flask db migrate
flask db upgrade
psql $DATABASE_URL -c "INSERT INTO templates (name, namespace, content) VALUES ('lede', 'washpost.hss.football_game.deciding_play', 'This is a sample template.')"
flask run
```

The issue is that as soon as I add a `docs.register` call, the program no longer works because the endpoint is not found. The endpoints are being registered as `TemplateResource:get` not `TemplateResource` or `templateresource`.

Any ideas on what to do? @sloria

**Comment by sloria** [comment]
I am unfamiliar with flask-classful and don't have time to investigate this right now. If you discover the issue, I'd be glad to review and merge a fix.

**Comment by AlJohri** [comment]
No problem @sloria. If you have an example working with any external class based rest framework (i.e. Flask-Restful), that would be a great start.

**Comment by rth** [comment]
> No problem @sloria. If you have an example working with any external class based rest framework (i.e. Flask-Restful), that would be a great start.

Here are a [few examples from github search](https://github.com/search?q=flask_restful+flask_apispec+&type=Code&utf8=%E2%9C%93) on using flask-apispec with flask-restful. Hope this helps..

**Comment by sloria** [comment]
Thanks @rth. That is a good place to look for examples.

**Comment by AlJohri** [comment]
Thanks! For future viewers the 18F example is pretty excellent: https://github.com/18F/openFEC
