### ISSUE TITLE
Swagger JSON for parameters in the header, path and query (at the same time) not reflecting code

### ISSUE THREAD

**Issue by tiangolo** [jmcarp/flask-apispec#63]
I can declare parameters in one location with `use_kwargs` from `header`, `query`, `path`, etc. But I can't declare specific parameters specific for one location in one section and for another at the same time. Only one of the `use_kwargs` ends up working. 

See: https://github.com/jmcarp/flask-apispec/issues/61 (I don't know why that issue is closed).

I tried specifying the header parameters in the `@doc` decorator and the JSON (body) parameters with `@use_kwargs`, and it works, as long as I don't declare any other parameter.

See:  and https://github.com/jmcarp/flask-apispec/issues/38

But if I declare header parameters using `@doc`, query (or json / body) parameters with `@use_kwargs` and also in the path (with the standard Flask router) the JSON documentation for the headers parameter disappears. I also tried documenting the path parameter in the `@doc` decorator but still, it doesn't appear in the final JSON.

Here's the first part of my function with the relevant code:

```python
authorization_headers = {
    'Authorization': {
        'description':
        'Authorization HTTP header with JWT token, like: Authorization: Bearer asdf.qwer.zxcv',
        'in':
        'header',
        'type':
        'string',
        'required':
        True
    }
}

@doc(
    description='Get processes with associated data by organization',
    params=authorization_headers.update({
        'organization_id': {
            'description':
            'The ID of the organization with the processes to retrieve',
            'type':
            'string',
            'required':
            True
        }
    }),
    tags=['processes'])
@app.route(
    f'{config.API_V2_STR}/organizations/<int:organization_id>/processes/')
@use_kwargs(
    {
        'from': fields.Int(missing=0),
        'size': fields.Int(missing=10),
        'no_activity': fields.Bool(),
        'productivity_id': fields.Int(),
        'category_id': fields.Int(),
    },
    locations=['query'])
@marshal_with(ProcessDocResultsSchema())
@jwt_required
def route_processes_organization_get(organization_id=None,
                                     size=None,
                                     no_activity=None,
                                     productivity_id=None,
                                     category_id=None,
                                     **kwargs):
    start_from = kwargs['from']

    ...
```

The corresponding JSON section is:

```json
"/api/v2/organizations/{organization_id}/processes/": {
      "get": {
        "description": "Get processes with associated data by organization", 
        "parameters": [
          {
            "default": 10, 
            "format": "int32", 
            "in": "query", 
            "name": "size", 
            "required": false, 
            "type": "integer"
          }, 
          {
            "format": "int32", 
            "in": "query", 
            "name": "category_id", 
            "required": false, 
            "type": "integer"
          }, 
          {
            "default": 0, 
            "format": "int32", 
            "in": "query", 
            "name": "from", 
            "required": false, 
            "type": "integer"
          }, 
          {
            "in": "query", 
            "name": "no_activity", 
            "required": false, 
            "type": "boolean"
          }, 
          {
            "format": "int32", 
            "in": "query", 
            "name": "productivity_id", 
            "required": false, 
            "type": "integer"
          }, 
          {
            "format": "int32", 
            "in": "path", 
            "name": "organization_id", 
            "required": true, 
            "type": "integer"
          }
        ], 
        "responses": 

    ...
```

**Comment by steven-upside** [comment]
If you replace 
```
@doc(
    description='Get processes with associated data by organization',
    params=authorization_headers.update({
<...>
})
```
with 
```
authorization_headers.update({
<...>
})
@doc(
    description='Get processes with associated data by organization',
    params=authorization_headers, 
    tags <...>
```
is your issue resolved? 

From python documentation, update returns `None` which seems like a likely cause of the symptoms you're describing
https://docs.python.org/3/library/stdtypes.html#dict.update

**Comment by tiangolo** [comment]
You are right @steven-upside . I was doing it wrong.

---

Now, to be able to use the integrated Swagger UI security authentication / authorization I'm using a different method.

We (me, actually) created a project generator using Flask-apispec and with all the integrations with Swagger configured. It's here: https://github.com/senseta-os/senseta-base-project

The relevant changes are mainly in:

https://github.com/senseta-os/senseta-base-project/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/api/api_v1/api_docs.py#L9

https://github.com/senseta-os/senseta-base-project/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/api/api_v1/api_docs.py#L30

https://github.com/senseta-os/senseta-base-project/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/api/api_v1/endpoints/token.py#L32

And here's an example on how to use it on an endpoint: https://github.com/senseta-os/senseta-base-project/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/api/api_v1/endpoints/token.py#L86

---

As my specific use case is solved now, I'll close this issue.
