### ISSUE TITLE
Upgrade swagger-ui

### ISSUE THREAD

**Issue by paxnovem** [jmcarp/flask-apispec#76]
Currently it appears that flask-apispec is using swagger-ui 2.1.3. Is there interest in upgrading this to 3.9.2 which still supports swagger 2.0 (https://github.com/swagger-api/swagger-ui#compatibility)?

**Comment by rth** [comment]
I think it would be quite useful, particularly since apispec supports openapi 3 while  swagger-ui 2.1.3 doesn't. A PR would be welcome.

**Comment by diogobaeder** [comment]
Hey @paxnovem , I noticed you forked the project and did the changes to include the new Swagger UI code. Do you plan to open a pull request here?

Thanks!

**Comment by diogobaeder** [comment]
Nice, thanks! :-)

**Comment by sloria** [comment]
swagger-ui is now updated to the latest version as of this writing (3.17.2).
