### ISSUE TITLE
Publish renamed egg

### ISSUE THREAD

**Issue by evocateur** [jmcarp/flask-apispec#8]
Any chance you could publish the renamed egg, or are there stability concerns remaining? I'd really like to start exploring this package, but it's awkward as a git clone.

**Comment by jmcarp** [comment]
Done: https://pypi.python.org/pypi/flask-apispec. I'm planning a change to the interface for registering view functions and classes in #6, but I don't have immediate plans to change the public interface otherwise. If you have thoughts about the package, I'd love to hear them!

**Comment by evocateur** [comment]
Thanks!
