### ISSUE TITLE
Incompatibility with webargs 2.0.0

### ISSUE THREAD

**Issue by jbwinters** [jmcarp/flask-apispec#84]
Looks like webargs 2.0.0 was released in February, and an API change broke compatibility with this library. Specifically, `Wrapper.call_view()` throws an exception in the `kwargs.update(parsed)` line because `parsed` is now an `UnmarshalResult` object instead of a dictionary. 

The resulting error message is useless: `dictionary update sequence element #0 has length 0; 2 is required`

Fixed for me by downgrading webargs, but it seems this library does not set an upper bound on the webargs version in setup.py so without explicitly installing the right version I had webargs 2.0.0 installed, which totally broke my server.

**Comment by sloria** [comment]
This has been fixed. I just tested with `webargs==2.0.0` and all tests pass.
