### ISSUE TITLE
Example clarification

### ISSUE THREAD

**Issue by jwaggs** [jmcarp/flask-apispec#86]
Hey guys, just a quick question... can you please clarify for me why you have two mismatching and seemingly conflicting class definitions within the same example? 

https://github.com/jmcarp/flask-apispec/blob/82992d264e9da77d6a93d3fe01b89a9f2a80f56d/examples/petstore.py#L17

https://github.com/jmcarp/flask-apispec/blob/82992d264e9da77d6a93d3fe01b89a9f2a80f56d/examples/petstore.py#L55

Was this intentional? Would you mind adding some clarification on what exactly is represented in this file?

**Comment by SlimaKCoder** [comment]
Look what is six: http://six.readthedocs.io/ and find what `six.with_metaclass` does.
